### ISSUE TITLE
Confirm slides are ready for Status of OGC API – Discrete Global Grid Systems (DGGS) presentation

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-track#24]

**Comment by ghobona** [comment]
Cc: @geofizzydrink

**Comment by ghobona** [comment]
Cc: @rggibb

**Comment by ghobona** [comment]
@rggibb Please confirm that your slides are ready.

**Comment by rggibb** [comment]
Slides have been uploaded to the Presentation folder. One file has both the Status slides and then the Block work slides
