### ISSUE TITLE
Confirm slides and handouts are ready for Practical work - Block 1: An update on OGC API - Processes

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-track#25]

**Comment by ghobona** [comment]
Cc: @bpross-52n @sptillma

**Comment by ghobona** [comment]
@bpross-52n @sptillma Please confirm that your slides are ready.

**Comment by bpross-52n** [comment]
@ghobona no, they are not yet ready. I have to see how I can fit this extra work in my already quite busy day, sorry..
